### ISSUE TITLE
InvalidOperationException in XML report in refdump

### ISSUE THREAD

**Issue by rainersigwald** [KirillOsenkov/MetadataTools#25]
I was poking at this file in the .NET 9-preview7 SDK, and hit this crash:

```sh-session
❯ refdump 'C:\Program Files\dotnet\sdk\9.0.100-preview.7.24407.12\Sdks\Microsoft.NET.Sdk\tools\net472\Microsoft.NET.Build.Tasks.dll' blah.xml
Microsoft.NET.Build.Tasks, Version=9.0.10.40712, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Deployment.DotNet.Releases, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Microsoft.DotNet.ApiCompat.Task, Version=9.0.100.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Microsoft.Extensions.DependencyModel, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Microsoft.NET.HostModel, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
NuGet.Common, Version=6.12.0.34, Culture=neutral, PublicKeyToken=31bf3856ad364e35
NuGet.Frameworks, Version=6.12.0.34, Culture=neutral, PublicKeyToken=31bf3856ad364e35
NuGet.LibraryModel, Version=6.12.0.34, Culture=neutral, PublicKeyToken=31bf3856ad364e35
NuGet.Packaging, Version=6.12.0.34, Culture=neutral, PublicKeyToken=31bf3856ad364e35
NuGet.ProjectModel, Version=6.12.0.34, Culture=neutral, PublicKeyToken=31bf3856ad364e35
NuGet.Versioning, Version=6.12.0.34, Culture=neutral, PublicKeyToken=31bf3856ad364e35
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
System.Reflection.Metadata, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

Unhandled exception. System.InvalidOperationException: Token EndDocument in state Document would result in an invalid XML document.
   at System.Xml.XmlWellFormedWriter.ThrowInvalidStateTransition(Token token, State currentState)
   at System.Xml.XmlWellFormedWriter.AdvanceState(Token token)
   at System.Xml.XmlWellFormedWriter.WriteEndDocument()
   at System.Xml.Linq.XDocument.WriteTo(XmlWriter writer)
   at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
   at RefDump.Dumper.Main(String[] args) in C:\MetadataTools\src\RefDump\Program.cs:line 31
```

This is with refdump as a global tool at 1.0.2.

(extremely low priority, I was curious what was in the XML)

**Comment by bbronisz** [comment]
I have the same issue. Refdump version 1.0.3. I'm on .NET 9.
